name: ktne
description: Keep Talking and Nobody Explodes - Busted

version: 0.0.1+0001

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.7.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "images/icon.png"
  # REMEMBER TO RUN "flutter pub pub run flutter_launcher_icons:main"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/
    - images/activities/
    - images/activities/Button/
    - images/activities/Keypads/
    - images/controls/
    - images/controls/dirty_page/
    - images/controls/ports/
  fonts:
   - family: Elite
     fonts:
      - asset: "fonts/SpecialElite-Regular.ttf"

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages